// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: docs/proto/v1/nonce.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Nonce_Get_FullMethodName    = "/grpc.v1.Nonce/Get"
	Nonce_Verify_FullMethodName = "/grpc.v1.Nonce/Verify"
)

// NonceClient is the client API for Nonce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NonceClient interface {
	Get(ctx context.Context, in *GetNonceRequest, opts ...grpc.CallOption) (*GetNonceResponse, error)
	Verify(ctx context.Context, in *VerifyNonceRequest, opts ...grpc.CallOption) (*VerifyNonceResponse, error)
}

type nonceClient struct {
	cc grpc.ClientConnInterface
}

func NewNonceClient(cc grpc.ClientConnInterface) NonceClient {
	return &nonceClient{cc}
}

func (c *nonceClient) Get(ctx context.Context, in *GetNonceRequest, opts ...grpc.CallOption) (*GetNonceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNonceResponse)
	err := c.cc.Invoke(ctx, Nonce_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nonceClient) Verify(ctx context.Context, in *VerifyNonceRequest, opts ...grpc.CallOption) (*VerifyNonceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyNonceResponse)
	err := c.cc.Invoke(ctx, Nonce_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NonceServer is the server API for Nonce service.
// All implementations must embed UnimplementedNonceServer
// for forward compatibility.
type NonceServer interface {
	Get(context.Context, *GetNonceRequest) (*GetNonceResponse, error)
	Verify(context.Context, *VerifyNonceRequest) (*VerifyNonceResponse, error)
	mustEmbedUnimplementedNonceServer()
}

// UnimplementedNonceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNonceServer struct{}

func (UnimplementedNonceServer) Get(context.Context, *GetNonceRequest) (*GetNonceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedNonceServer) Verify(context.Context, *VerifyNonceRequest) (*VerifyNonceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedNonceServer) mustEmbedUnimplementedNonceServer() {}
func (UnimplementedNonceServer) testEmbeddedByValue()               {}

// UnsafeNonceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NonceServer will
// result in compilation errors.
type UnsafeNonceServer interface {
	mustEmbedUnimplementedNonceServer()
}

func RegisterNonceServer(s grpc.ServiceRegistrar, srv NonceServer) {
	// If the following call pancis, it indicates UnimplementedNonceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Nonce_ServiceDesc, srv)
}

func _Nonce_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNonceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NonceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nonce_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NonceServer).Get(ctx, req.(*GetNonceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nonce_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyNonceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NonceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nonce_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NonceServer).Verify(ctx, req.(*VerifyNonceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Nonce_ServiceDesc is the grpc.ServiceDesc for Nonce service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Nonce_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.v1.Nonce",
	HandlerType: (*NonceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Nonce_Get_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _Nonce_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "docs/proto/v1/nonce.proto",
}
