// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: docs/proto/v1/nonce.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNonceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicAddres  string                 `protobuf:"bytes,1,opt,name=publicAddres,proto3" json:"publicAddres,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNonceRequest) Reset() {
	*x = GetNonceRequest{}
	mi := &file_docs_proto_v1_nonce_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNonceRequest) ProtoMessage() {}

func (x *GetNonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_nonce_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNonceRequest.ProtoReflect.Descriptor instead.
func (*GetNonceRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_nonce_proto_rawDescGZIP(), []int{0}
}

func (x *GetNonceRequest) GetPublicAddres() string {
	if x != nil {
		return x.PublicAddres
	}
	return ""
}

type VerifyNonceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicAddres  string                 `protobuf:"bytes,1,opt,name=publicAddres,proto3" json:"publicAddres,omitempty"`
	SignedNonce   string                 `protobuf:"bytes,2,opt,name=signedNonce,proto3" json:"signedNonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyNonceRequest) Reset() {
	*x = VerifyNonceRequest{}
	mi := &file_docs_proto_v1_nonce_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyNonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNonceRequest) ProtoMessage() {}

func (x *VerifyNonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_nonce_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNonceRequest.ProtoReflect.Descriptor instead.
func (*VerifyNonceRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_nonce_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyNonceRequest) GetPublicAddres() string {
	if x != nil {
		return x.PublicAddres
	}
	return ""
}

func (x *VerifyNonceRequest) GetSignedNonce() string {
	if x != nil {
		return x.SignedNonce
	}
	return ""
}

type GetNonceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNonceResponse) Reset() {
	*x = GetNonceResponse{}
	mi := &file_docs_proto_v1_nonce_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNonceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNonceResponse) ProtoMessage() {}

func (x *GetNonceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_nonce_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNonceResponse.ProtoReflect.Descriptor instead.
func (*GetNonceResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_nonce_proto_rawDescGZIP(), []int{2}
}

func (x *GetNonceResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type VerifyNonceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succsess      bool                   `protobuf:"varint,1,opt,name=succsess,proto3" json:"succsess,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyNonceResponse) Reset() {
	*x = VerifyNonceResponse{}
	mi := &file_docs_proto_v1_nonce_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyNonceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyNonceResponse) ProtoMessage() {}

func (x *VerifyNonceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_nonce_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyNonceResponse.ProtoReflect.Descriptor instead.
func (*VerifyNonceResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_nonce_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyNonceResponse) GetSuccsess() bool {
	if x != nil {
		return x.Succsess
	}
	return false
}

func (x *VerifyNonceResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_docs_proto_v1_nonce_proto protoreflect.FileDescriptor

const file_docs_proto_v1_nonce_proto_rawDesc = "" +
	"\n" +
	"\x19docs/proto/v1/nonce.proto\x12\agrpc.v1\"5\n" +
	"\x0fGetNonceRequest\x12\"\n" +
	"\fpublicAddres\x18\x01 \x01(\tR\fpublicAddres\"Z\n" +
	"\x12VerifyNonceRequest\x12\"\n" +
	"\fpublicAddres\x18\x01 \x01(\tR\fpublicAddres\x12 \n" +
	"\vsignedNonce\x18\x02 \x01(\tR\vsignedNonce\"(\n" +
	"\x10GetNonceResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\"K\n" +
	"\x13VerifyNonceResponse\x12\x1a\n" +
	"\bsuccsess\x18\x01 \x01(\bR\bsuccsess\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress2\x88\x01\n" +
	"\x05Nonce\x12:\n" +
	"\x03Get\x12\x18.grpc.v1.GetNonceRequest\x1a\x19.grpc.v1.GetNonceResponse\x12C\n" +
	"\x06Verify\x12\x1b.grpc.v1.VerifyNonceRequest\x1a\x1c.grpc.v1.VerifyNonceResponseB\x0fZ\rdocs/proto/v1b\x06proto3"

var (
	file_docs_proto_v1_nonce_proto_rawDescOnce sync.Once
	file_docs_proto_v1_nonce_proto_rawDescData []byte
)

func file_docs_proto_v1_nonce_proto_rawDescGZIP() []byte {
	file_docs_proto_v1_nonce_proto_rawDescOnce.Do(func() {
		file_docs_proto_v1_nonce_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_proto_v1_nonce_proto_rawDesc), len(file_docs_proto_v1_nonce_proto_rawDesc)))
	})
	return file_docs_proto_v1_nonce_proto_rawDescData
}

var file_docs_proto_v1_nonce_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_docs_proto_v1_nonce_proto_goTypes = []any{
	(*GetNonceRequest)(nil),     // 0: grpc.v1.GetNonceRequest
	(*VerifyNonceRequest)(nil),  // 1: grpc.v1.VerifyNonceRequest
	(*GetNonceResponse)(nil),    // 2: grpc.v1.GetNonceResponse
	(*VerifyNonceResponse)(nil), // 3: grpc.v1.VerifyNonceResponse
}
var file_docs_proto_v1_nonce_proto_depIdxs = []int32{
	0, // 0: grpc.v1.Nonce.Get:input_type -> grpc.v1.GetNonceRequest
	1, // 1: grpc.v1.Nonce.Verify:input_type -> grpc.v1.VerifyNonceRequest
	2, // 2: grpc.v1.Nonce.Get:output_type -> grpc.v1.GetNonceResponse
	3, // 3: grpc.v1.Nonce.Verify:output_type -> grpc.v1.VerifyNonceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_docs_proto_v1_nonce_proto_init() }
func file_docs_proto_v1_nonce_proto_init() {
	if File_docs_proto_v1_nonce_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_v1_nonce_proto_rawDesc), len(file_docs_proto_v1_nonce_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_v1_nonce_proto_goTypes,
		DependencyIndexes: file_docs_proto_v1_nonce_proto_depIdxs,
		MessageInfos:      file_docs_proto_v1_nonce_proto_msgTypes,
	}.Build()
	File_docs_proto_v1_nonce_proto = out.File
	file_docs_proto_v1_nonce_proto_goTypes = nil
	file_docs_proto_v1_nonce_proto_depIdxs = nil
}
